### ISSUE TITLE
The Handy Support

### ISSUE THREAD

**Issue by Sonderxl** [Aspher0/FFXIV_Vibe_Plugin#1]
i got everything working up to triggers, I'm not getting any feedback. Someone mentioned that it might be because of some way the plugin handles it internally and to post an issue on the plugin repo.

![Image](https://github.com/user-attachments/assets/d08edd1e-55b8-4555-8ee4-b00b60e2b2fa)

![Image](https://github.com/user-attachments/assets/625247ae-9c2e-492c-ade0-2a32d6f84171)

**Comment by Aspher0** [comment]
Hello, sorry for the late reply.
Unfortunately, if it's a bug with code I won't be able to fix it, I'm just maintaining the plugin in its state and it's way too much spaghettini tortelini code since it's a decompiled version.
For now I have to update it to API13 and I don't know when I can do that.

**Comment by Aspher0** [comment]
Hello!
I've updated the plugin to API13, can you tell me if you can control your toy from the intiface central at least ? If yes, can you try clicking the "Test trigger" button and also try to control the toy via the plugin's "Devices" tab ?
If it really doesnt work i'm afraid I can't do much, not only because I do not own that toy and cannot test it, and also because of what I said above.

**Comment by Sonderxl** [comment]
> Hello! I've updated the plugin to API13, can you tell me if you can control your toy from the intiface central at least ? If yes, can you try clicking the "Test trigger" button and also try to control the toy via the plugin's "Devices" tab ? If it really doesnt work i'm afraid I can't do much, not only because I do not own that toy and cannot test it, and also because of what I said above.

yeah the handy still doesn't work the other toys i have work fine i guess it has something to do with the motor, but thank for taking th e time to look into it.

**Comment by Aspher0** [comment]
Sorry I couldn't help!
